service: linkManagement


#custom:
#  pythonRequirements:
#    dockerizePip: true

provider:
  name: aws
  runtime: python3.8
  endpointType: REGIONAL
  iamRoleStatements:
      - Effect: Allow
        Action: 
          - "dynamodb:scan"
          - "dynamodb:PutItem"
          - "dynamodb:GetItem"
        Resource: arn:aws:dynamodb:us-east-1:612185335394:table/linkStorage
functions:

  shorten_link:
    handler: shortener/shorten.handler
    events:
      - http: 
          path: /
          method: post
          authorizer:
            arn: arn:aws:lambda:us-east-1:612185335394:function:utilities-dev-authorizer
    environment:
      CLIENT_URL_ROOT: https://form.basementremodeling.com
      INTERNAL_URL_ROOT: https://form.basementremodeling.com
    
  lenghten_link:
    handler: shortener/lengthen.handler
    events:
      - http: 
          path: /{proxy+}
          method: any
    environment:
      URL_ROOT: https://api.builteasy.com 

resources: 
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: linkStorage
        AttributeDefinitions:
          - AttributeName: link
            AttributeType: S
        KeySchema:
          - AttributeName: link
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2

#plugins:
#  - serverless-python-requirements